/* generated by https://transform.tools/json-to-typescript */

export interface IAssetInfo {
    epic: string
    instrumentName: string
    instrumentType: string
    expiry: string
    high: number
    low: number
    percentageChange: number
    netChange: number
    updateTime: string
    updateTimeUTC: string
    bid: number
    offer: number
    delayTime: number
    streamingPricesAvailable: boolean
    marketStatus: string
    scalingFactor: number
    marketInfo: MarketInfo
}

export interface MarketInfo {
    instrument: Instrument
    dealingRules: DealingRules
    snapshot: Snapshot
}

export interface Instrument {
    epic: string
    expiry: string
    name: string
    forceOpenAllowed: boolean
    stopsLimitsAllowed: boolean
    lotSize: number
    unit: string
    type: string
    controlledRiskAllowed: boolean
    streamingPricesAvailable: boolean
    marketId: string
    currencies: Currency[]
    marginDepositBands: MarginDepositBand[]
    margin: number
    slippageFactor: SlippageFactor
    openingHours: OpeningHours
    expiryDetails: ExpiryDetails
    rolloverDetails: any
    newsCode: string
    chartCode: string
    country: string
    valueOfOnePip: any
    onePipMeans: any
    contractSize: any
    specialInfo: string[]
}

export interface Currency {
    code: string
    name: string
    symbol: string
    baseExchangeRate: number
    exchangeRate: number
    isDefault: boolean
}

export interface MarginDepositBand {
    min: number
    max?: number
    margin: number
}

export interface SlippageFactor {
    unit: string
    value: number
}

export interface OpeningHours {
    marketTimes: MarketTime[]
}

export interface MarketTime {
    openTime: string
    closeTime: string
}

export interface ExpiryDetails {
    lastDealingDate: string
    settlementInfo: string
}

export interface DealingRules {
    minStepDistance: MinStepDistance
    minDealSize: MinDealSize
    minControlledRiskStopDistance: MinControlledRiskStopDistance
    minNormalStopOrLimitDistance: MinNormalStopOrLimitDistance
    maxStopOrLimitDistance: MaxStopOrLimitDistance
    controlledRiskSpacing: ControlledRiskSpacing
    marketOrderPreference: string
}

export interface MinStepDistance {
    unit: string
    value: number
}

export interface MinDealSize {
    unit: string
    value: number
}

export interface MinControlledRiskStopDistance {
    unit: string
    value: number
}

export interface MinNormalStopOrLimitDistance {
    unit: string
    value: number
}

export interface MaxStopOrLimitDistance {
    unit: string
    value: number
}

export interface ControlledRiskSpacing {
    unit: string
    value: number
}

export interface Snapshot {
    marketStatus: string
    netChange: number
    percentageChange: number
    updateTime: string
    delayTime: number
    bid: number
    offer: number
    high: number
    low: number
    binaryOdds: any
    decimalPlacesFactor: number
    scalingFactor: number
    controlledRiskExtraSpread: number
}

/* generated by https://transform.tools/json-to-typescript */

/*
{
  "epic": "UA.D.AAPL.DAILY.IP",
  "instrumentName": "Apple Inc (All Sessions)",
  "instrumentType": "SHARES",
  "expiry": "DFB",
  "high": 18248,
  "low": 17816,
  "percentageChange": 1.72,
  "netChange": 307.5,
  "updateTime": "19:13:20",
  "updateTimeUTC": "19:13:20",
  "bid": 18226,
  "offer": 18235,
  "delayTime": 0,
  "streamingPricesAvailable": false,
  "marketStatus": "TRADEABLE",
  "scalingFactor": 1,
  "marketInfo": {
    "instrument": {
      "epic": "UA.D.AAPL.DAILY.IP",
      "expiry": "DFB",
      "name": "Apple Inc (All Sessions)",
      "forceOpenAllowed": true,
      "stopsLimitsAllowed": true,
      "lotSize": 1,
      "unit": "AMOUNT",
      "type": "SHARES",
      "controlledRiskAllowed": true,
      "streamingPricesAvailable": false,
      "marketId": "AAPL-US",
      "currencies": [
        {
          "code": "$.",
          "name": "USD",
          "symbol": "$",
          "baseExchangeRate": 1.230239,
          "exchangeRate": 0.66,
          "isDefault": false
        },
        {
          "code": "E.",
          "name": "EUR",
          "symbol": "E",
          "baseExchangeRate": 1.1496,
          "exchangeRate": 0.9,
          "isDefault": false
        },
        {
          "code": "#.",
          "name": "GBP",
          "symbol": "£",
          "baseExchangeRate": 1,
          "exchangeRate": 1,
          "isDefault": true
        }
      ],
      "marginDepositBands": [
        {
          "min": 0,
          "max": 137,
          "margin": 20
        },
        {
          "min": 137,
          "max": 685,
          "margin": 20
        },
        {
          "min": 685,
          "max": 2740,
          "margin": 40
        },
        {
          "min": 2740,
          "max": null,
          "margin": 75
        }
      ],
      "margin": 20,
      "slippageFactor": {
        "unit": "pct",
        "value": 100
      },
      "openingHours": {
        "marketTimes": [
          {
            "openTime": "09:00",
            "closeTime": "01:00"
          }
        ]
      },
      "expiryDetails": {
        "lastDealingDate": "06/04/29 21:00",
        "settlementInfo": "DFBs settle on the Last Dealing Day at the closing market bid/offer price of the share, plus or minus half the IG spread. "
      },
      "rolloverDetails": null,
      "newsCode": "AAPL.O",
      "chartCode": "AAPL",
      "country": "US",
      "valueOfOnePip": null,
      "onePipMeans": null,
      "contractSize": null,
      "specialInfo": [
        "DEFAULT KNOCK OUT LEVEL DISTANCE",
        "MAX KNOCK OUT LEVEL DISTANCE",
        "Please note US (All Sessions) shares close early at 22:00 UK time on Friday evenings."
      ]
    },
    "dealingRules": {
      "minStepDistance": {
        "unit": "POINTS",
        "value": 50
      },
      "minDealSize": {
        "unit": "POINTS",
        "value": 0.5
      },
      "minControlledRiskStopDistance": {
        "unit": "PERCENTAGE",
        "value": 10
      },
      "minNormalStopOrLimitDistance": {
        "unit": "POINTS",
        "value": 1
      },
      "maxStopOrLimitDistance": {
        "unit": "PERCENTAGE",
        "value": 90
      },
      "controlledRiskSpacing": {
        "unit": "POINTS",
        "value": 150
      },
      "marketOrderPreference": "AVAILABLE_DEFAULT_OFF"
    },
    "snapshot": {
      "marketStatus": "TRADEABLE",
      "netChange": 305,
      "percentageChange": 1.7,
      "updateTime": "19:13:38",
      "delayTime": 0,
      "bid": 18223,
      "offer": 18233,
      "high": 18248,
      "low": 17816,
      "binaryOdds": null,
      "decimalPlacesFactor": 1,
      "scalingFactor": 1,
      "controlledRiskExtraSpread": 0
    }
  }
}
*/