/* generated by https://transform.tools/json-to-typescript */

export interface IPositionInfo {
    position: Position
    market: Market
}

export interface Position {
    contractSize: number
    createdDate: string
    dealId: string
    dealSize: number
    direction: 'BUY' | 'SELL'
    limitLevel: any
    openLevel: number
    currency: string
    controlledRisk: boolean
    stopLevel: any
    trailingStep: any
    trailingStopDistance: any
    limitedRiskPremium: any
}

export interface Market {
    instrumentName: string
    expiry: string
    epic: string
    instrumentType: string
    lotSize: number
    high: number
    low: number
    percentageChange: number
    netChange: number
    bid: number
    offer: number
    updateTime: string
    delayTime: number
    streamingPricesAvailable: boolean
    marketStatus: string
    scalingFactor: number
}

/* generated by https://transform.tools/json-to-typescript */

/*
{
  "position": {
    "contractSize": 1,
    "createdDate": "2022/10/17 16:06:34:000",
    "dealId": "DIAAAAKUAS2EPAQ",
    "dealSize": 1,
    "direction": "BUY",
    "limitLevel": null,
    "openLevel": 3370,
    "currency": "GBP",
    "controlledRisk": false,
    "stopLevel": null,
    "trailingStep": null,
    "trailingStopDistance": null,
    "limitedRiskPremium": null
  },
  "market": {
    "instrumentName": "DHL Group",
    "expiry": "DFB",
    "epic": "ED.D.DPW.DAILY.IP",
    "instrumentType": "SHARES",
    "lotSize": 1,
    "high": 3737,
    "low": 3689,
    "percentageChange": -0.19,
    "netChange": -7,
    "bid": 3709,
    "offer": 3717,
    "updateTime": "16:35:12",
    "delayTime": 0,
    "streamingPricesAvailable": false,
    "marketStatus": "EDITS_ONLY",
    "scalingFactor": 1
  }
}
*/