# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI/CD Settings (DII)

on:
  push:
    branches:
      - deploy-production

jobs:
  deploy:
    name: SSH Connection
    runs-on: ubuntu-latest
    steps:
      - name: SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST  }}
          username: ${{ secrets.USERNAME  }}
          key: ${{ secrets.SSH_RSA_PRIVATE_KEY  }}
          port: 22
          command_timeout: 500m
          script: |
            sudo docker system prune --force

            sudo rm -rf DII-event-listener

            sudo git clone https://${{ secrets.REPO_TOKEN  }}@github.com/IXily/DII-event-listener.git

            sudo chown -R ${{ secrets.USERNAME  }} ./DII-event-listener

            cd DII-event-listener

            sudo git checkout deploy-production
            
            sudo su -c 'echo "WALLET_PRIVATE_KEY=\"${{secrets.WALLET_PRIVATE_KEY}}\"" > .env && echo "PKP_KEY=\"${{secrets.PKP_KEY}}\"" >> .env && echo "SLACK_WEBHOOK_URL=\"${{secrets.SLACK_WEBHOOK_URL}}\"" >> .env'

            sudo sh ./scripts/pull_spinup-live.sh